# Generated by Django 3.2.20 on 2023-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20230812_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='exam',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='td',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='tp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
